Resolução de testes
robertofrega/data-collection-test pull request #11
Opened 2017-12-03 17:36 UTC by dratto

2017-12-20 13:47 UTC, BetoFrega requested changes

2017-12-20 13:47 UTC, BetoFrega commented on 008/tagueamento.js
> +  $('#mensagem').bind('DOMSubtreeModified', function() {
@dratto Considerando que o evento utilizado está em processo de se tornar obsoleto, gostaria de recomendar uma implementação mais robusta?

2017-12-20 13:47 UTC, BetoFrega commented on 002/tagueamento.js
> +  btn.on('click', function() {
@dratto Esta não era a solução esperada para o teste. Gostaria de rever?

2017-12-21 01:50 UTC, dratto commented
@robertofrega Correções e melhorias efetuadas.

2018-01-08 14:25 UTC, BetoFrega approved these changes

2018-01-12 11:43 UTC, closed without merging