Resolução do Teste
robertofrega/data-collection-test pull request #12
Opened 2018-01-06 22:28 UTC by luancurti

2018-01-12 16:39 UTC, BetoFrega requested changes
@luancurti Faltaram algumas validações no seu QA.
Pode verificar os comentários, por favor?

2018-01-12 16:39 UTC, BetoFrega commented on 008/tagueamento.js
> +messageFatherElement.addEventListener('DOMNodeInserted', logMessageOnInsertMessage, false);
@luancurti O evento adicionado está em processo de remoção dos padrões Web. Gostaria de sugerir outra solução?

Refs.:
- https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events

2018-01-12 16:39 UTC, BetoFrega commented on 002/tagueamento.js
> +  function logPreviousSiblingElementTextOnClick ($event) {
Não apresenta o resultado esperado para o teste.

2018-01-12 16:39 UTC, robertofrega commented on 001/tagueamento.js
> +    return Array.prototype.map.call(buttonElements, getButtonName);
Caso não houvesse o requisito de cobertura para o IE, você consideraria fazer esta ilnha de outra forma?

2018-01-12 16:39 UTC, robertofrega commented on 001/tagueamento.js
> +(function()  {
Pequeno erro de estilo aqui

2018-01-12 16:39 UTC, robertofrega commented on 001/tagueamento.js
> +    $event.target && $event.target.nodeName === TARGET_NODE_NAME && console.log($event.target.innerText);
Evitar condicionais que não têm cara de condicional

2018-01-12 16:39 UTC, robertofrega commented on 003/tagueamento.js
> +'use strict';
"Documente uma explicação para o retorno no próprio código." não foi coberto

2018-01-12 16:39 UTC, robertofrega commented on 003/tagueamento.js
> +    var clickedButtonsText = Array.prototype.map.call(clickedButtons, getButtonName)
As variáveis aqui são arrays e possuem o método chamado.
Por que você usou o método do prototype?

2018-01-12 16:39 UTC, robertofrega commented on 005/tagueamento.js
> +      console.log($event.target.previousSibling.innerText);
Não é o resultado esperado

2018-01-12 16:39 UTC, robertofrega commented on 006/tagueamento.js
> +      console.log($event.target.innerText.split('-').pop());
Não segue o solicitado

2018-01-12 16:39 UTC, robertofrega commented on 007/tagueamento.js
> +    if ($event.target && $event.target.nodeName === TARGET_NODE_NAME) {
Não está passando corretamente

2018-01-12 16:39 UTC, robertofrega commented on 008/tagueamento.js
> +  messageFatherElement.addEventListener('DOMNodeInserted', logMessageOnInsertMessage, false);
O evento utilizado está se tornando obsoleto. Recomenda outra solução?

2018-01-16 02:25 UTC, luancurti commented on 003/tagueamento.js
> +    var clickedButtonsText = Array.prototype.map.call(clickedButtons, getButtonName)
Por causa da Limitação do IE

2018-01-16 02:26 UTC, luancurti commented on 001/tagueamento.js
> +(function()  {
Corrigido

2018-01-16 02:28 UTC, luancurti commented on 001/tagueamento.js
> +    return Array.prototype.map.call(buttonElements, getButtonName);
Utilizaria Array.from(document.querySelectorAll('#botoes')).map(function (element) { return element.innerText });

2018-01-16 02:29 UTC, luancurti commented on 001/tagueamento.js
> +    $event.target && $event.target.nodeName === TARGET_NODE_NAME && console.log($event.target.innerText);
Corrigido

2018-01-16 02:48 UTC, luancurti commented on 002/tagueamento.js
> +  function logPreviousSiblingElementTextOnClick ($event) {
Corrigido

2018-01-16 02:51 UTC, luancurti commented on 005/tagueamento.js
> +      console.log($event.target.previousSibling.innerText);
Corrigido

2018-01-20 18:43 UTC, closed without merging